---
title: "TwiBot-22 EDA"
output:
  pdf_document
---

```{r, echo=FALSE, message=FALSE} 
library(tidyverse)
library(corrgram)
```

# •__Histogram of Days since created__


```{r, echo=FALSE}

small_user_final <- read.csv("/Users/manan/Desktop/Research/Learning/small_user_final.csv")

small_edge <- read.csv("/Users/manan/Desktop/Research/Learning/small_edge.csv")

ggplot(data = small_user_final, mapping = aes(x = days_since_created)) + 
  geom_histogram(binwidth = 150) +
  scale_x_continuous(breaks = seq(0, max(small_user_final$days_since_created), 500))

```


```{r, echo=FALSE}
ggplot(data = small_user_final) +
  geom_point(mapping = aes(x = days_since_created, y = tweet_count))

ggplot(data = small_user_final, mapping = aes(x = days_since_created)) +
  geom_freqpoly(binwidth=150)

ggplot(data = small_user_final) +
  geom_point(mapping = aes(x = following_count, y=tweet_count))

ggplot(data = small_user_final) +
  geom_point(mapping = aes(x = followers_count, y=tweet_count))

corrgram(small_user_final, order=TRUE, lower.panel=panel.shade,
          upper.panel=panel.pie, text.panel=panel.txt,)

ggplot(small_user_final, aes(x = days_since_created)) +
  geom_histogram(aes(color = label, fill = label),
                 position = "identity", bins = 30, alpha = 0.4) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800"))


ggplot(small_user_final, aes(x = description)) +
  geom_histogram(aes(color = label, fill = label),
                 position = "identity", bins = 30, alpha = 0.5) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800"))

ggplot(small_user_final, aes(x = pinned_tweet_id)) +
  geom_histogram(aes(color = label, fill = label),
                 position = "identity", bins = 30, alpha = 0.5) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800"))


ggplot(small_user_final, aes(x = verified)) +
  geom_histogram(aes(color = label, fill = label),
                 position = "identity", bins = 30, alpha = 0.5) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800"))

```
